### ISSUE TITLE
Add possibility to get more results

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#16]
Right now the app only prints the first 10 results. Should we add a possibility for the user to see the next 10 results as long as they want? So after the app prints the results, it prompts the user something like "do you want to see 10 more results, do another search or quit?"

**Comment by kanerv** [comment]
As I wrote in #9, I modified the program so that it print's the number of articles matching the query. Depending on the number, it then prints the preview of either all of them or the first 10. I tried to add your suggestion of printing more articles but, I could not get a try-except function to work properly (in case the user does not answer with e.g. **"y"** or **"n"** to **"Do you want to see more articles?"** we need to catch it so that the program does not shut down). I also think our current printing is quite neat as it is, so I did not feel like spending too much time on this.

**Comment by saanahyttinen** [comment]
I think this is a good idea but not sure how it could be done... I also agree with Kanerva that our printing is looking quite nice as it is already, good job!
