### ISSUE TITLE
Stemmer

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#19]
Stemming: Your search engine will not only find documents, in which your search terms are exact matches, but other inflected forms will match as well. For instance, if you work on English data, a search for house will find documents containing house, houses, housing etc. Similarly a search for houses will return the same documents.

**Comment by TuukkaOT** [comment]
I managed to do a stem search app. It is only a start, and it doesn't work well, but I don't have time to continue right now. Feel free to make it better and/or add it to the main program. I will try and develop it more during the afternoon. Also, I had to scrap the iterator for reading the file, so don't use the wikipedia data dump unless you manage to make it work with the 100,000 line limit.

**Comment by saanahyttinen** [comment]
Great! At least the stemmer now seems to convert the words in the documents into stems! I'm not sure if I understood correctly what we went through during the lecture about this, but I remember something about adding a character (like * etc.) to the end of every stem? I'm not sure if that is needed though... Also I don't really know how to make this better right now, so I tried focusing on the multi-word search (#18), but I didn't manage to get that working either. :D

**Comment by kanerv** [comment]
I think I'm missing a module or something for this program, since I get the following error code:

LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/Users/kanerva/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.8/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.8/share/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

I don't know what's wrong since I did not manage to get it to work even with the help of https://www.nltk.org/data.html... Sadly Raul wasn't at the zoom room anymore so that I could have asked for help. Sorry, I'm totally useless with the stemmer at least for now :(

**Comment by TuukkaOT** [comment]
It seems you're missing something for the nltk word_tokenizer. I installed nltk with pip installer. Maybe that could help?

**Comment by saanahyttinen** [comment]
Now we are able to search for exact matches OR exact stems if the user adds '_s' to the end of the stem. I was in Raul's meeting and I think he said this is what we were supposed to do in the assignment, but I'm thinking if there would be a way to implement the stemmer in a way that if the user searches for example 'hous_s', they would get for example 'house', 'houses', 'housing' as results? Or was this required?
