### ISSUE TITLE
[L] Create a program/function that retrieves data from Rotten Tomatoes

### ISSUE THREAD

**Issue by kanerv** [kanerv/TuukkaSaanaKanerva#37]
We planned to mine data from the Rotten Tomato website using beautifulsoup (https://www.blog.pythonlibrary.org/2013/11/06/python-101-how-to-grab-data-from-rottentomatoes/). Store the data in a dictionary containing the name of the movie as keys and the content of critics' consensus as values.

**Comment by TuukkaOT** [comment]
So Rotten Tomatoes API isn't accessible for us, at least on a short notice, because you need to request a key. We could still try to access the critics consensuses manually though. I made a little app from the web retriever from earlier that extracts some text from links from the Guardian headline page. I will still try to make it work with rotten tomatoes tonight.

**Comment by TuukkaOT** [comment]
Now the scraper app retrieves top 10 box office hits from Rotten Tomatoes and a short synopsis of the film. I realised new films usually don't have a critics consensus yet, so for the time being I just extracted the synopsis. I had to use json module to get it because the synopsis was embedded in the code in a way that I wasn't able to extract it just with BeautifulSoup.

**Comment by TuukkaOT** [comment]
I managed to get the app to print the critics consensuses from the 100 best films list. It doesn't print them all completely so there is still some tweaking to be done. I capped the parsing at first 10 articles so it doesn't take so much time to run the app.

EDIT: Now realised the critics consensuses don't correspond to the links either. Gonna try and fix that now.

**Comment by TuukkaOT** [comment]
Okay now the app retrieves the URLs, extracts titles and critics consensuses from film pages, and they are in correct order. Yippee!

**Comment by kanerv** [comment]
> Okay now the app retrieves the URLs, extracts titles and critics consensuses from film pages, and they are in correct order. Yippee!

Well done!!! 🎉

**Comment by saanahyttinen** [comment]
Wow this looks good!
