### ISSUE TITLE
[S/M] Get rid of empty graphs if search term not found.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#57]
The page shows one of the graphs as empty and the other as a broken image if the search term is not found.

**Comment by saanahyttinen** [comment]
I fixed this by making an extra html-page that is rendered when there are no results found. However, I don't know if this happened earlier or if this exact change caused it, but it looks like the wildcard search is not working for not-exact words like 'mov' or 'movi' anymore ('movie' works)! 

I was thinking it could be caused by this change because I added the following line that might be limited to work only for our exact search:
    if query not in terms:
        return render_template('indexnoresults.html', matches=[], query=query)

So I tried adding an OR to the if-clause, so it would include also our wc-search, but I'm not sure if I understand the functioning of the wc-search well enough and could not make it work... I'm so sorry if this change broke it!

**Comment by saanahyttinen** [comment]
I had to move the following lines to the search()-function to make the wildcard search also return the no results-template:
 wc_query = query+".*"   #adds the wildcard notation and finds matching words from the data
    global wc_words
    wc_words = [w for w in terms if re.fullmatch(wc_query, w)]  #this line is copied from the group "wewhoshallnotbenamed"

Also deleted old code we used for printing the "no results" before.

**Comment by saanahyttinen** [comment]
I'm thinking if we should actually delete the test_query()-function and move the rest of the code from there to the search()-function? Would this work or make the code clearer, what do you guys think? If not we can of course leave it as it is.

**Comment by kanerv** [comment]
> I'm thinking if we should actually delete the test_query()-function and move the rest of the code from there to the search()-function? Would this work or make the code clearer, what do you guys think? If not we can of course leave it as it is.

I think this was a good idea, so I went for it. I also fixed the issue with the first view
