### ISSUE TITLE
Add functionality to "headlines_yle_guardian.py" if we want to use it for this weeks assignment

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#6]
I made a test program that prints 10 headlines from YLE and Guardian, and it allows the user to open both websites on their web browser. If we want to use it for the assignment, maybe we could add some functionality. For example, we could use BeautifulSoup to extract some other information connected to the headlines, e.g. extract links and print headlines with ordinal numbers. Then the user could write, e.g., G6 to open the article corresponding to the 6th headline on the Guardian website.

**Comment by kanerv** [comment]
The program looks great!! You've done amazing work Tuukka, thank you!

I tried to create a for loop that would extract the URL's found on https://yle.fi/uutiset/tuoreimmat. However, I could not figure out how to navigate the data structure and get the links successfully. I wrote my code in a separate file (url_retriever.py) which is in our test directory. I believe the problem is in line 16, since my program just returns a list full of None objects. Does any of you have suggestions on what's going wrong?

Thanks for your help!

**Comment by TuukkaOT** [comment]
Thanks Kanerva :)
I looked at the code and did a small change. What I did was, I copied the exact adress of the first headline (https://yle.fi/urheilu/3-11753636), and then I went to the source code of yle.fi/tuoreimmat and searched for that address. I pasted the name of the class of that element to your for-loop, and now it works.
-Tuukka

**Comment by TuukkaOT** [comment]
I was thinking, could we incorporate your code in the main program so that it prints the links after the headlines? It might be too difficult at least for me to try figure out how to give the user an option to open every link, but printing them sounds doable. Maybe we could use a dictionary with the headlines as keys and links as values?

**Comment by kanerv** [comment]
I was actually thinking about using the dictionary as well, but if I remember right, they are not ordered and thus it would have been hard to include in your original idea of letting the user choose which article they want to open in a browser using ordinal numbers. However, I like your idea of including the links in the printout.

**Comment by TuukkaOT** [comment]
Oh yeh I think you're right. <del>Do you have some idea how we could iterate through both the "soup.find_all(...)" commands and add the results to one dictionary?</del>
EDIT: I tried this by just adding your code and at the end put:
for i in lista:
                    for c in linkit:
                        print(i)
                        print(c)
This print it correctly but 10x. I'm sure there is some stupid amateur mistake here, but it's close :)

EDIT2: I found a thing called enumerate and managed to print them both. There's some issues with the format of the link addresses, so feel free to make it better :D I will push it to the repo now.

**Comment by TuukkaOT** [comment]
I added the links now. Some of the links are missing "http://". But I realised that at least in my command line, the links that have http://, actually are hyperlinks and you can click them. So we need to somehow fix the rest of the links so that they are complete. And maybe we can add this to the YLE luetuimmat and Guardian as well?
I will stop doing this now, so I won't hog all the jobs. Sorry if I'm a little too eager with these :D

**Comment by kanerv** [comment]
Sorry should have read your comments beforehand, but I have now done exactly what you suggested!
- I fixed the link retriever so that it adds the beginning (https://yle.fi) if it's missing. In my command line, none of them aren't hyperlinks, but at least they are now consistent in style.
- I also added the functionality and printing to Yle luetuimmat ja The guardian. I hope everything works as it should. 

(I used your way of printing, Tuukka, since it worked out beautifully. No need for playing around with dictionaries this time!)

It's amazing how much effort you put into this Tuukka! Thank you for that!

**Comment by TuukkaOT** [comment]
Great, it works perfectly now! Maybe the automatic hyperlink thingy is some Linux feature, because now all the links open if I just press ctrl while I click them.

**Comment by saanahyttinen** [comment]
Wow you guys have done amazing things here! Thank you!
I will have time to work on this better during the following days so what do you think I should add to the program? It seems to work perfectly already and do all the things that were asked. 💯 
Do you think adding another website would make it more confusing? That way I could practice the web retrieval code too... Or another thing I was thinking would be maybe making some changes to the code so that some parts of it would be defined as functions that could be called for in the main program? That is if there is some parts of code that reoccur in the same way multiple times, like for examle now the beautiful printing of the "yleisradio" logo.
Let me know what you think would be appropriate :)

**Comment by TuukkaOT** [comment]
Separating the app into more functions sounds good! And I think you can definitely add websites without making it confusing. If you want to use some ASCII shazam, this is what I used: https://patorjk.com/software/taag/

**Comment by saanahyttinen** [comment]
Great! I'll see what I can do with it!

**Comment by saanahyttinen** [comment]
I created a program that extracts the 10 first news titles from Reuters. I tried to get the links as well but it did not work yet so any tips for how to make that work are appreciated! :) 
If you wonder, I actually used a bit different way to access the website than you guys since this is what I learned from the NLTK book chapter 3.1. This program can be found on the Test_files as url_retriever_saana.py.

I also tried to add my Reuters program to our main program (headlines_yle_guardian.py), but there are some problems I could not resolve yet. Will try to do that tomorrow!

**Comment by TuukkaOT** [comment]
I tried a few different tags but none of them give anything. The one you used, headline-content, seems like the most promising, but I don't know why it isn't working.

**Comment by saanahyttinen** [comment]
I decided to change my program to get news titles from www.bbc.com/world instead of Reuters because with that I managed to get the link extracting to work as well.

I also switched the Reuters search in the headlines_yle_guardian.py to BBC and changed the name of the file accordingly.

**Comment by saanahyttinen** [comment]
Week 1 task done.
