### ISSUE TITLE
Print the contents of the retrieved documents

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#9]
2. Your search application should print the contents of the retrieved documents. (A vector consisting of ones and zeros won't do!) If there are too many matching documents, maybe you want to show only the top n documents. (Still you could print out how many matching documents there are in total.) If the documents are long, maybe you want to truncate the output to the m first words or characters only.

**Comment by saanahyttinen** [comment]
hakukone.py now prints the contents of the matching document, but the amount of possible matches, or the length of the contents of a document shown in the results is not limited.

**Comment by kanerv** [comment]
I made some additions:
- The program now tells how many articles matched the query. If there were 10 or fewer articles, the program prints a preview of all of them, and if there were more, it only prints a preview of the 10 first articles. <strike>_**HOWEVER**_ now we don't really need the try-except part, since the program would never get to that point even though the hits_list was empty. I added an if-clause to correctly print something when a search returns no results.</strike> NEVERMIND! I did more testing and we **cannot** get rid of the try-except function! 
-  I deleted the **print("Rewritten:", rewrite_query(query))** because I don't think it was needed. Please correct me if I was mistaken!
- I also added a minor print **"We are ready to search!"** to make the thread more user friendly to navigate.
